services:
  web:
    image: ghcr.io/bastien-louche/cicd:latest
    build: .
    ports:
      - "80:3000"
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1