services:
  web:
    image: ghcr.io/bastien-louche/cicd:latest
    build: .
    ports:
      - "80:3000"
      
  db:
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cube
      MYSQL_USER: cube
      MYSQL_PASSWORD: cube
      volumes:
        - ./docker/db:/var/lib/mysql

  adminer:
    image: adminer
    ports: 
      - 8080:80

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1