name: docker
on: [push]
jobs:
  buildDocker:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
   - uses: docker/setup-qemu-action@v2
   - uses: docker/setup-buildx-action@v2
   - name: Login to Docker
      uses: docker/login-action@v2
        with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.AUTH_TOKEN }}
   - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: next/web-cicd:latest