name: CI/CD
on: [push]
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-node@v3
       with:
        node-version: '18'
     - uses: actions/cache@v3
       with:
         path:
           node_modules
           ~/.cache/Cypress
         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
     - run: npm install
     - run: npm run build
     - run: ls -lah

  test:
   runs-on: ubuntu-latest
   needs: build
   steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-node@v3
       with:
        node-version: '18'
     - uses: actions/cache@v3
       with:
         path:
           node_modules
           ~/.cache/Cypress
         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
     - run: npm run e2e:headless
     - uses: actions/upload-artifact@v3
       with:
         name: e2e-video
         path: cypress/videos/
 
      